---
- name: install nano 
  hosts: linux
  remote_user: root

  tasks:
  - name: Ensure apache is at the latest version
    yum: 
      name: nano
      state: latest
- name: install git
  hosts: linux
  remote_user: root

  tasks:
  - name: install the latest git version
    yum:
      name: git
      state: latest
